msg_separator: "\n\n〰️〰️〰️〰️〰️〰️〰️〰️〰️️〰️〰️〰️️〰️〰️\n"

user_location:
  menu: "Меню"
  maps: "Карта"
  profile: "Профиль"
  tasks_menu_message: "📜 *Квесты* 📟 *Задания* 📆 *Ежедневки* 📜"

callback_char:
  cancel: "cancel"
  backpack_moving: "backpackMoving"
  goods_moving: "goodsMoving"
  eat_food: "eatFood"
  delete_item: "deleteItem"
  dress_good: "dressGood"
  take_off_good: "takeOffGood"
  change_left_hand: "changeLeftHand"
  change_right_hand: "changeRightHand"
  change_avatar: "changeAvatar"
  description: "description"
  workbench: "workbench"
  receipt: "receipt"
  put_item: "putItem"
  put_count_item: "putCountItem"
  make_new_item: "makeNewItem"
  throw_out_item: "throwOutItem"
  count_of_delete: "countOfDelete"
  buy_home: "buyHome"
  user_done_quest: "user_done_quest"
  user_get_quest: "user_get_quest"
  quest: "quest"
  quests: "quests"

quest_statuses:
  completed: "✅ Выполнен"
  processed: "✴️ В работе"
  new: "🆕 Новый"
  completed_emoji: "✅"
  processed_emoji: "✴️"
  new_emoji: "🆕"

elem:
  black: "⬛"
  brown: "🟫"
  red: "🟥"
  purple: "🟪"
  orange: "🟧"
  yellow: "🟨"
  green: "🟩"
  blue: "🟦"
  white: "⬜"
  door: "🚪"
  day_window: "🌁 🏙️ 🏞️"
  evening_window: "🌆 🌇 🌄 🌅"
  night_window: "🌃 🌌 🌉 🎑"

message:
  list_of_avatar: "🐶 🐱 🐭 🐹 🐰 🦊 🐻 🐼 ‍️🐨 🐯 🦁 🐮 🐷 🐸 🐵 🐦 🐧 🐔 🐤 🐥 🦆 🐴 🦄 🐺 🐗 🐝 🦋 🐛 🐌 🐞 🪲 🪰 🐜 🕷 🪳 🦖 🦕 🐙 🦀 🐟 🐠 🐡 🦭"
  doing:
    up: "🔼"
    down: "🔽"
    left: "◀️️"
    right: "▶️"
  emoji:
    water: "\U0001F7E6"
    clock: "🕦"
    casino: "🎰"
    forbidden: "🚫"
    wrench: "🔧"
    offline: "📳"
    online: "📴"
    stop_use: "🚷"
    exclamation_mark: "❗"
    hand: "👋"
    foot: "\U0001F9B6"
    quest: "📟"
  user:
    online: "📴 ♻️ 📳"
    offline: "📳 ♻️ 📴"

errors:
  no_quest_item: "Здесь нет доски с квестами!"
  user_not_has_item_in_hand: "Нельзя взять без инструмента в руке"
  user_has_other_item: "Сначала снимите предмет, чтоб надеть другой"
  user_did_not_task: "Задание не выполнено!"